#!/usr/bin/env zsh


save=false

for arg in "$@"; do
    case "$arg" in
        -s)
            save=true
            ;;
        -h|--help)
            echo "Usage: $(basename "$0") [-s]"
            echo
            echo "  -s    Save to ~/Pictures/Screenshots and copy to clipboard"
            echo "        Otherwise, copy to clipboard only"
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Usage: $(basename "$0") [-s]"
            exit 1
            ;;
    esac
done

if $save; then
    dir="$HOME/Pictures/Screenshots"
    mkdir -p "$dir"

    file="$dir/$(date +"%Y-%m-%d_%H-%M-%S").png"

    grim "$file"
    wl-copy < "$file"

    notify-send -i "shotwell" -a "Hyprcap" \
        "Screenshot taken" \
        "Saved to disk & clipboard"
else
    grim - | wl-copy

    notify-send -i "shotwell" -a "Hyprcap" \
        "Screenshot taken" \
        "Copied to clipboard"
fi