#!/usr/bin/env bash

# checks if wf-recorder is an active process
# if so, stops hyprcap
# otherwise, starts hyprcap

if pgrep -x wf-recorder >/dev/null; then
    exec hyprcap rec-stop
else
    exec hyprcap rec-start -c -n
fi
