#!/usr/bin/env zsh

# OBSOLETE
# OBSOLETE
# OBSOLETE
# OBSOLETE

if [[ "$(obs-cli record status)" == "started" ]]; then
    if obs-cli record stop; then
        notify-send -i "obs" "Recording Stopped" \
            "OBS recording has been stopped."
    fi
else
    if obs-cli record start; then
        notify-send -i "obs" "Recording Started" \
            "OBS is now recording."
    fi
fi