format = """
╭─ $directory$git_branch$git_commit$git_status
╰─$character """

[directory]
format = "[$path]($style)"
style = "bold cyan"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = " on [$branch]($style)"
style = "bold purple"

[git_commit]
commit_hash_length = 7
format = "@[$hash]($style)"
style = "bold yellow"
only_detached=false

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "bold yellow"

[cmd_duration]
min_time = 2000
format = " took [$duration]($style)"
style = "bold yellow"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
