ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=""

plugins=(
    git
    sudo
    archlinux
)

source "$ZSH/oh-my-zsh.sh"

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"


export EDITOR=nvim
export VISUAL=nvim

alias update='yay -Syu'
alias cd='z'
alias cdi='zi'
alias ls='eza --icons=always'
alias ll='eza -lah --icons=always'
alias la='eza -a --icons=always'
alias lt='eza --tree --level=2 --icons=always'
alias lta='eza --tree --level=2 -a --icons=always'
alias cat='bat'
alias grep='rg'

fastfetch

export PATH="$HOME/.local/bin:$PATH"

